<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="C:\Users\mefek\OneDrive\Документы\My Web Sites\Index.cshtml" Link="Index.cshtml" />
  </ItemGroup>

</Project>
